services:
  - type: web
    name: todo_app
    env: python
    static_publish_path: staticfiles
    buildCommand: ""
    startCommand: gunicorn todo_project.wsgi:application
    preDeployCommand: python manage.py migrate
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: todo_project.settings
