services:
  - type: web
    name: todo_app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn todo_project.wsgi:application
    preDeployCommand: python manage.py migrate
